import "./globals.css";
import type { Metadata } from "next";
import { Inter, Noto_Serif } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Serif({subsets:['latin'], weight:'500', style:'italic'})

export const metadata: Metadata = {
  title: " Studio L'Amour'",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
